"""§10 — official questions ship with a verified link + check date, and the
provenance the student sees never claims "official" without that link.
"""

from __future__ import annotations

from fastapi.testclient import TestClient


def _official_base(client: TestClient, first_lesson: str) -> dict:
    lesson = client.get(f"/api/curriculum/lessons/{first_lesson}").json()
    source = lesson.get("source") or {}
    return {
        "prompt": "سؤال وزاري تجريبي: ما قانون نيوتن الثاني في الحركة؟",
        "options": ["كتلة × تسارع", "كتلة ÷ تسارع", "سرعة ÷ زمن", "قوة × زمن"],
        "answer_index": 0,
        "explanation": "القوة المحصلة = كتلة الجسم × تسارعه.",
        "difficulty": 3,
        "topic": "نيوتن",
        "source_kind": "official",
        "source_id": source.get("id"),
    }


def test_official_requires_verified_link(
    client: TestClient, admin_headers: dict[str, str], first_lesson: str
) -> None:
    base = _official_base(client, first_lesson)
    assert base["source_id"], "seeded lesson lost its source"

    # no source_url -> the question must not enter the bank at all (§10)
    rejected = client.post("/api/exams/bank", headers=admin_headers, json=dict(base))
    assert rejected.status_code == 422, rejected.text

    base["source_url"] = "https://example.com/ministry-sample.pdf"
    created = client.post("/api/exams/bank", headers=admin_headers, json=base)
    assert created.status_code == 200, created.text
    assert created.json()["status"] == "validated"

    listed = client.get(
        "/api/exams/bank", params={"q": "قانون نيوتن الثاني"}, headers=admin_headers
    ).json()
    item = next(i for i in listed["items"] if i["source_kind"] == "official")
    assert item["source_url"].startswith("https://")
    assert item["checked_at"], "official question without checked_at"


def test_quiz_provenance_reaches_student(
    client: TestClient, demo_headers: dict[str, str], first_lesson: str
) -> None:
    quiz = client.post(
        "/api/quiz/generate",
        headers=demo_headers,
        json={"lesson_id": first_lesson, "count": 2},
    )
    assert quiz.status_code == 200, quiz.text
    payload = client.get(f"/api/quiz/{quiz.json()['id']}", headers=demo_headers)
    assert payload.status_code == 200, payload.text
    questions = payload.json()["questions"]
    assert questions
    for question in questions:
        prov = question["provenance"]
        assert prov["label"]
        assert prov["kind"] in ("official", "ai", "external", "bank", "manual")
        # a question generated by AI never claims an official source
        if prov["kind"] != "official":
            assert prov["url"] == ""


def test_official_without_link_is_demoted() -> None:
    from app.db import Question
    from app.services.bank import provenance

    question = Question(
        prompt="سؤال بلا رابط موثّق — يجب ألا يُعرض كمصدر وزاري.",
        source_kind="official",
        source_url="",
        source_id=None,
    )
    prov = provenance(question)
    assert prov["kind"] == "ai"
    assert prov["label"] == "توليد AI"
    assert prov["url"] == ""
